FROM registry.redhat.io/openshift4/microshift-bootc-rhel9:v4.18

# Unset proxy env vars
ENV NO_PROXY=
ENV HTTP_PROXY=
ENV HTTPS_PROXY=

# Reset dnf
RUN dnf -y clean all &&\
    rm -rf /etc/yum.repos.d/unsigned.repo

# Ensure flightctl agent is installed
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Add flightctl agent config
ADD .flightctl-agent-config/config.yaml /etc/flightctl/

# Ignore registry certs
ADD ocp-internal-registry.conf /etc/containers/registries.conf.d/999-ocp-internal-registry.conf

# Add registry auth
ADD .registry-auth/auth.json /usr/lib/container-auth.json
RUN chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Need a pull secret
COPY .pull-secret/pull-secret.txt /etc/crio/openshift-pull-secret

# MTU magic
COPY ovn.yaml /etc/microshift/ovn.yaml

# Disable Microshift in this image
RUN systemctl mask microshift.service

# Disable auto-updating
RUN systemctl mask bootc-fetch-apply-updates.timer

# Lint the build
RUN bootc container lint