---
apiVersion: batch/v1
kind: Job
metadata:
  name: start-flightctl-cli-build
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: build-full-access
      containers:
        - name: start-flightctl-cli-build
          image: registry.redhat.io/openshift4/ose-cli:latest
          command: ["oc",  "start-build", "flightctl-cli"]
      restartPolicy: OnFailure

