---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rhem-cli-web-terminal
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'rhem-cli-web-terminal:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  source:
    type: Binary
    configMaps:
      - configMap:
          name: build-from-image
        destinationDir: '.'