{
 "title": "Student Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "student",
    "label": "Student",
    "query": {
     "query": "label_values(probe_success{job=\"rhem-virtual-machines\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Student $student", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "student" },
  {
   "title": "RHEM Virtual Machine",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"rhem-on-rhel-ssh.wksp-{{ .Values.guid }}-$student.svc.cluster.local:22\", job=\"rhem-virtual-machines\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RHEM on RHEL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"rhem-on-rhel.wksp-{{ .Values.guid }}-$student.svc.cluster.local:443\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QCOW2 Export",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"import-disk-image.wksp-{{ .Values.guid }}-$student.svc.cluster.local:8888/disk.qcow2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drone Tracker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"drone-tracker.wksp-{{ .Values.guid }}-$student.svc.cluster.local:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drone Cam",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"drone-cam.wksp-{{ .Values.guid }}-$student.svc.cluster.local:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}