---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-flightctl-agent-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: route-reader
      containers:
        - name: create-flightctl-agent-config
          image: image-registry.openshift-image-registry.svc:5000/student-services/flightctl-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              cd /tmp
              FLIGHTCTL_USERNAME=$(cat /tmp/openshift-auth/username)
              FLIGHTCTL_PASSWORD=$(cat /tmp/openshift-auth/password)
              until FLIGHTCTL_API_URL=$(oc get route flightctl-api-route -n open-cluster-management -o go-template='{{ "{{" }}.spec.host{{ "}}" }}') && [ -n "$FLIGHTCTL_API_URL" ]; do
                echo "Route not found, retrying in 5 seconds..."
                sleep 5
              done

              until flightctl login "https://$FLIGHTCTL_API_URL" --username "$FLIGHTCTL_USERNAME" --password "$FLIGHTCTL_PASSWORD" --insecure-skip-tls-verify; do
                echo "Login failed, retrying in 5 seconds..."
                sleep 5
              done

              flightctl certificate request --signer=enrollment --expiration=365d --output=embedded > config.yaml
              echo '---
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: flightctl-agent-config
              data:
                config.yaml: |
                  spec-fetch-interval: 0m10s
                  status-update-interval: 0m10s' > /tmp/configmap.yaml
              cat config.yaml | sed 's/^/    /g' >> /tmp/configmap.yaml
              oc apply -f configmap.yaml
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: dot-config
              mountPath: /.config
            - name: openshift-auth
              readOnly: true
              mountPath: /tmp/openshift-auth
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
        - name: dot-config
          emptyDir:
            sizeLimit: 100Mi
        - name: openshift-auth
          secret:
            secretName: openshift-auth

