---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-images-rbac
  namespace: openshift-gitops
  labels:
    application: build-images-rbac
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: student-services
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/rhpds/lb2517-edge-fleet-gitops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/build-images-rbac/
    helm:
