---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-flightctl-agent-config
  namespace: openshift-gitops
  labels:
    application: create-flightctl-agent-config
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: student-services
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/rhpds/edge-fleet-gitops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/create-flightctl-agent-config/
    helm:
      values: |
        openshiftAuth:
{{- with .Values.openshiftAuth }}
            username: {{ .username }}
            password: {{ .password }}
{{- end }}
            

