---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: openshift-gitops
  labels:
    application: pipelines
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/rhpds/edge-fleet-gitops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/pipelines/
    helm:
