---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: populate-pull-secret
  namespace: openshift-gitops
  labels:
    application: populate-pull-secret
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: student-services
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/rhpds/edge-fleet-gitops.git
    targetRevision: {{ .Values.gitBranch | default "main" }}
    path: charts/populate-pull-secret/
    helm:
