{{- range .Values.students }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ . }}-bootdisk
  namespace: {{ . }}
  annotations:
    "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ $.Values.virtualMachines.storageSize }}
    volumeMode: Block
    storageClassName: {{ $.Values.virtualMachines.storageClass }}
  source:
    pvc:
      name: {{ $.Values.virtualMachines.sourcePvcName }}
      namespace: {{ $.Values.virtualMachines.sourcePvcNamespace }}
{{- end }}