---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pull-secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "list", "apply", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pull-secret-reader
  namespace: openshift-config
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]