---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flightctl-admin-role-binding
subjects:
{{- $userCount := int .Values.numberStudents }}
{{- range $index := until $userCount }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ add $index 1 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flightctl-admin