FROM registry.redhat.io/rhel9/rhel-bootc:9.5

# Install flightctl agent
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Add flightctl agent config
ADD .flightctl-agent-config/config.yaml /etc/flightctl/

# Add registry auth
ADD .registry-auth/auth.json /usr/lib/container-auth.json
RUN chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Ignore registry certs
ADD ocp-internal-registry.conf /etc/containers/registries.conf.d/999-ocp-internal-registry.conf

# Allow apps through the firewall
RUN firewall-offline-cmd --zone=public --add-port=30000/tcp
RUN firewall-offline-cmd --zone=public --add-port=8080/tcp

# Add quadlet files
COPY point-of-sale.kube /etc/containers/systemd/point-of-sale.kube
COPY point-of-sale.yaml /etc/containers/systemd/point-of-sale.yaml

# Disable auto-updates
RUN systemctl mask bootc-fetch-apply-updates.timer

# Lint the build
RUN bootc container lint