FROM registry.redhat.io/rhel9/rhel-bootc:9.5

# Install flightctl agent
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Add flightctl agent config
ADD .flightctl-agent-config/config.yaml /etc/flightctl/

# Add registry auth
ADD .registry-auth/auth.json /usr/lib/container-auth.json
RUN chmod 0600 /usr/lib/container-auth.json && \
    ln -sr /usr/lib/container-auth.json /etc/ostree/auth.json

# Ignore registry certs
ADD ocp-internal-registry.conf /etc/containers/registries.conf.d/999-ocp-internal-registry.conf

# Add quadlet files
COPY point-of-sale.kube /etc/containers/systemd/point-of-sale.kube
COPY point-of-sale.yaml /etc/containers/systemd/point-of-sale.yaml

# Install podman-compose
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf -y clean all && \
    rm -rf /var/cache/dnf/*
RUN rm /etc/rhsm-host
RUN dnf -y install podman-compose && \
    dnf -y clean all && \
    rm -rf /var/cache/dnf/* && \
    rm -rf /etc/rhsm
RUN systemctl enable podman.service

# Disable auto-updates
RUN systemctl mask bootc-fetch-apply-updates.timer

# Lint the build
RUN bootc container lint