---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-registry-auth-configmap
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: registry-auth-sa
      containers:
        - name: populate-registry-auth-configmap
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              oc registry login --to=/tmp/auth.json
              cat /tmp/auth.json
              if ! oc create configmap registry-auth --from-file=/tmp/auth.json; then
                echo "ConfigMap already exists, updating it..."
                oc create configmap registry-auth --from-file=/tmp/auth.json --dry-run=client -o yaml | oc apply -f -
              fi
      restartPolicy: OnFailure

