---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-auth-role
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - patch
  - update