---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-full-access-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-full-access
subjects:
- kind: ServiceAccount
  name: build-full-access
  namespace: {{ .Release.Namespace }}