---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wksp-{{ .Values.tenant }}-{{ .Values.guid }}-edit
  namespace: wksp-{{ .Values.tenant }}-{{ .Values.guid }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.tenant }}-{{ .Values.guid }}