---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-job-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch"]