---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-job-rb
subjects:
  - kind: ServiceAccount
    name: tekton-job-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: tekton-job-role
  apiGroup: rbac.authorization.k8s.io